#!/usr/bin/ruby

CITY = {}
CITIES = []
ARGF.each do |line|
   fields = line.split
   CITY[fields[2]] = [fields[4].to_f, fields[6].to_f]
  CITIES << fields[2]
end

puts '\begin{tabular}{|l|' + 'r|'*CITIES.size + '}\hline'
puts " & #{CITIES.join(" & ")} \\\\ \\hline"
CITIES.each_index do |i|
  print "#{CITIES[i]}"
  ci = CITY[CITIES[i]]
  CITIES.each_index do |j|
    if i != j
      cj = CITY[CITIES[j]]
      printf " & %3.0f", Math.hypot(ci[0]-cj[0], ci[1]-cj[1]) / 1000.0
    else
      print " &"
    end
  end
  puts ' \\\\'
end
puts '\hline\end{tabular}'

